### ISSUE TITLE
Namespaced temps

### ISSUE THREAD

**Issue by jensljungblad** [jpignata/temping#17]
Weird request perhaps, but would it be possible to allow for creating namespaced temps?

``` ruby
Temping.create :"foo/bar"
```

This generates a `NameError: wrong constant name Foo::Bar`

**Comment by grn** [comment]
What are you trying to accomplish with this? Does you code expect model classes to be defined in particular namespaces?

**Comment by jensljungblad** [comment]
Yes, something like that. Kinda like how Rails creates a module when you generate a namespaced model:

```ruby
module MyNamespace
  def self.table_prefix
    "my_namespace"
  end
end

module MyNamespace
  class MyClass < ActiveRecord::Base; end
end
```

But it's a very minor issue :) And can be easily solved by mixing in the module in the temping class.

**Comment by dorner** [comment]
I have a use case for this as well.

**Comment by kitop** [comment]
@dorner Can you give an example so we can work with that? Thanks!

**Comment by dorner** [comment]
It's admittedly very specific. It's a library that takes a "configuration name" and instantiates a class that matches that name in a particular namespace. So for example, if I want to create a task that acts on widgets called "CreateWidget", the service class would look for a class called "Tasks::Widget::CreateWidget".

I guess we could fudge this by changing it to some kind of class registry, but that seems like unnecessary work since we can leverage Rails autoloading to do essentially the same thing.

**Comment by kitop** [comment]
@dorner Thanks for the explanation.
If you wanna share that version or send a PR, that will be greatly appreciated :)

**Comment by dorner** [comment]
In my case I just make use of RSpec's `stub_const`, which makes this really easy. Not sure how you'd implement it easily without it.

**Comment by kitop** [comment]
Thanks for the reply. That's a good idea.
Without RSpec, I think we'd have to do a bit more work when creating and removing constants, going module by module and building it if it doesn't exist. 

I'll try to work on it soon.
