### ISSUE TITLE
Alternative for Temping

### ISSUE THREAD

**Issue by kgathi2** [jpignata/temping#61]
Is there a good alternative for this gem. PR's not being merged. Is it abandoned?

**Comment by wintersolutions** [comment]
Although I see that there is movement [now](https://github.com/jpignata/temping/pull/59#issuecomment-938754270) in this project, I've changed to [with_model](https://github.com/Casecommons/with_model) in the meantime.

**Comment by tomshy** [comment]
Looking for one too. This one is not being maintained and it's not working well with rails 7. 

It depends on the now missing 'ActiveSupport::Dependencies::Reference' - https://github.com/rails/rails/commit/14d4edd7c3b06e82e1fcef54fa0b4453315c35fd

**Comment by dmytro-savochkin** [comment]
Okay, I think I've fixed everything that had been reported so far.
The new version of temping (4.0.0), which supports Ruby 3+ and Rails 7+, is on Rubygems finally.
Feel free to try it if you'd like to, also any issues or PRs are welcome too.

Meanwhile I am gonna close this issue since it's no longer relevant (Temping is maintained now).
