### ISSUE TITLE
Running with Rails main

### ISSUE THREAD

**Issue by trobrock** [jpignata/temping#96]
We run off of Rails main and since the move to the 8.0 version I cannot install the latest version of this gem.

Would you be opposed to changing the version restriction to not have an upper-bound? Happy to submit the PR if so.

**Comment by dmytro-savochkin** [comment]
I like it to be upper-bounded because this gem heavily depends on ActiveRecord.
The idea is that when a new minor version of Rails is released I can quickly rerun the tests, fix the incompatibilities, and then release a new version of Temping.
According to my experience both 7.0 and 7.1 have introduced incompatibilities that required changes to Temping for it to continue working so there is a good chance that 8.0 might have them too.

If I remove the upper bound completely and it will be used against `main` branch of Rails there is even higher chance of some problems, after all `main` of `rails` is a constantly evolving thing where bugs can be added and then quickly fixed, etc. I don't think this gem is ready for such a fast paced development.

**Comment by trobrock** [comment]
@dmytro-savochkin that's fair. What's the best approach for me to help testing on ActiveRecord 8? Is it just update the gemspec and run the test suite, then send a PR?

**Comment by dmytro-savochkin** [comment]
Would it work for you to fork this gem, remove the upper bound in `temping.gemspec`, and then use your forked version like `gem 'temping', git: 'https://github.com/trobrock/temping'` for your project where you rely on `main` of `rails`?

**Comment by trobrock** [comment]
@dmytro-savochkin that's what I'm doing now. I would prefer to not have to use gems from Github and it'll require me to regularly merge your main branch in to mine, but if there is no path to supporting Rails 8 here then that's what I'll do.

**Comment by dmytro-savochkin** [comment]
Btw may I ask you why are you using `main` branch of Rails and not a specific version? I think I've never seen this for medium- or big-sized Rails-based projects.

**Comment by dmytro-savochkin** [comment]
Got it, thanks. In any case I am afraid I can't offer any other solution than forking.

**Comment by trobrock** [comment]
@dmytro-savochkin ok, so there are no plans to support AR 7.2+ then? If that's the case then I'll need to find a new solution.

**Comment by dmytro-savochkin** [comment]
There are plans to support each major and minor version of Rails (including 7.2 and 8.0) as soon as it's officially released.
